// ========================================
// TEMAS DE COLORES PARA LANDING PAGES
// ========================================

import { LandingTheme, LandingThemeType } from './types'

export const LANDING_THEMES: Record<LandingThemeType, LandingTheme> = {
  // ========================================
  // PRODUCTOS DE SEGUROS
  // ========================================
  auto: {
    id: 'auto',
    name: 'Seguro Auto',
    primaryColor: '#007AFF',
    secondaryColor: '#0056B3',
    gradient: 'from-blue-500 to-blue-600',
    gradientDark: 'from-blue-600 to-blue-800',
    icon: 'Car',
    emoji: '🚗',
  },
  hogar: {
    id: 'hogar',
    name: 'Seguro Hogar',
    primaryColor: '#34C759',
    secondaryColor: '#2DA44E',
    gradient: 'from-emerald-500 to-emerald-600',
    gradientDark: 'from-emerald-600 to-emerald-800',
    icon: 'Home',
    emoji: '🏠',
  },
  salud: {
    id: 'salud',
    name: 'Seguro Salud',
    primaryColor: '#AF52DE',
    secondaryColor: '#9B59B6',
    gradient: 'from-violet-500 to-violet-600',
    gradientDark: 'from-violet-600 to-violet-800',
    icon: 'HeartPulse',
    emoji: '💜',
  },
  vida: {
    id: 'vida',
    name: 'Seguro Vida',
    primaryColor: '#FF2D55',
    secondaryColor: '#E91E63',
    gradient: 'from-rose-500 to-rose-600',
    gradientDark: 'from-rose-600 to-rose-800',
    icon: 'Heart',
    emoji: '❤️',
  },
  decesos: {
    id: 'decesos',
    name: 'Seguro Decesos',
    primaryColor: '#8E8E93',
    secondaryColor: '#636366',
    gradient: 'from-gray-500 to-gray-600',
    gradientDark: 'from-gray-600 to-gray-800',
    icon: 'Flower2',
    emoji: '🕊️',
  },
  mascotas: {
    id: 'mascotas',
    name: 'Seguro Mascotas',
    primaryColor: '#FF9500',
    secondaryColor: '#E67E00',
    gradient: 'from-orange-500 to-orange-600',
    gradientDark: 'from-orange-600 to-orange-800',
    icon: 'PawPrint',
    emoji: '🐾',
  },
  comercio: {
    id: 'comercio',
    name: 'Seguro Comercio',
    primaryColor: '#5856D6',
    secondaryColor: '#4B49C6',
    gradient: 'from-indigo-500 to-indigo-600',
    gradientDark: 'from-indigo-600 to-indigo-800',
    icon: 'Store',
    emoji: '🏪',
  },
  comunidades: {
    id: 'comunidades',
    name: 'Seguro Comunidades',
    primaryColor: '#5AC8FA',
    secondaryColor: '#4AADE6',
    gradient: 'from-cyan-500 to-cyan-600',
    gradientDark: 'from-cyan-600 to-cyan-800',
    icon: 'Building2',
    emoji: '🏢',
  },
  viaje: {
    id: 'viaje',
    name: 'Seguro Viaje',
    primaryColor: '#00C7BE',
    secondaryColor: '#00AFA7',
    gradient: 'from-teal-500 to-teal-600',
    gradientDark: 'from-teal-600 to-teal-800',
    icon: 'Plane',
    emoji: '✈️',
  },
  moto: {
    id: 'moto',
    name: 'Seguro Moto',
    primaryColor: '#FF6B35',
    secondaryColor: '#E55A2B',
    gradient: 'from-orange-500 to-red-500',
    gradientDark: 'from-orange-600 to-red-700',
    icon: 'Bike',
    emoji: '🏍️',
  },
  accidentes: {
    id: 'accidentes',
    name: 'Seguro Accidentes',
    primaryColor: '#FF3B30',
    secondaryColor: '#D63027',
    gradient: 'from-red-500 to-red-600',
    gradientDark: 'from-red-600 to-red-800',
    icon: 'ShieldAlert',
    emoji: '🛡️',
  },
  'rc-profesional': {
    id: 'rc-profesional',
    name: 'RC Profesional',
    primaryColor: '#30B0C7',
    secondaryColor: '#2699AD',
    gradient: 'from-cyan-500 to-blue-500',
    gradientDark: 'from-cyan-600 to-blue-700',
    icon: 'Briefcase',
    emoji: '💼',
  },

  // ========================================
  // SEGMENTOS DE CLIENTES
  // ========================================
  familias: {
    id: 'familias',
    name: 'Familias',
    primaryColor: '#34C759',
    secondaryColor: '#2DA44E',
    gradient: 'from-green-500 to-emerald-500',
    gradientDark: 'from-green-600 to-emerald-700',
    icon: 'Users',
    emoji: '👨‍👩‍👧‍👦',
  },
  autonomos: {
    id: 'autonomos',
    name: 'Autónomos',
    primaryColor: '#FF9500',
    secondaryColor: '#E67E00',
    gradient: 'from-amber-500 to-orange-500',
    gradientDark: 'from-amber-600 to-orange-700',
    icon: 'User',
    emoji: '💼',
  },
  empresas: {
    id: 'empresas',
    name: 'Empresas',
    primaryColor: '#5856D6',
    secondaryColor: '#4B49C6',
    gradient: 'from-indigo-500 to-purple-500',
    gradientDark: 'from-indigo-600 to-purple-700',
    icon: 'Building',
    emoji: '🏢',
  },
  jovenes: {
    id: 'jovenes',
    name: 'Jóvenes',
    primaryColor: '#FF2D55',
    secondaryColor: '#E91E63',
    gradient: 'from-pink-500 to-rose-500',
    gradientDark: 'from-pink-600 to-rose-700',
    icon: 'Sparkles',
    emoji: '🎓',
  },
  'mayores-65': {
    id: 'mayores-65',
    name: 'Mayores +65',
    primaryColor: '#007AFF',
    secondaryColor: '#0056B3',
    gradient: 'from-blue-500 to-indigo-500',
    gradientDark: 'from-blue-600 to-indigo-700',
    icon: 'Heart',
    emoji: '🧓',
  },
  'nuevos-conductores': {
    id: 'nuevos-conductores',
    name: 'Nuevos Conductores',
    primaryColor: '#FF6B35',
    secondaryColor: '#E55A2B',
    gradient: 'from-orange-500 to-amber-500',
    gradientDark: 'from-orange-600 to-amber-700',
    icon: 'Car',
    emoji: '🚗',
  },
  extranjeros: {
    id: 'extranjeros',
    name: 'Extranjeros',
    primaryColor: '#00C7BE',
    secondaryColor: '#00AFA7',
    gradient: 'from-teal-500 to-cyan-500',
    gradientDark: 'from-teal-600 to-cyan-700',
    icon: 'Globe',
    emoji: '🌍',
  },
  parejas: {
    id: 'parejas',
    name: 'Parejas',
    primaryColor: '#FF2D55',
    secondaryColor: '#FF6B8A',
    gradient: 'from-pink-500 to-red-400',
    gradientDark: 'from-pink-600 to-red-600',
    icon: 'Heart',
    emoji: '💑',
    particleEffect: 'hearts',
  },

  // ========================================
  // CAMPAÑAS TEMPORALES
  // ========================================
  'black-friday': {
    id: 'black-friday',
    name: 'Black Friday',
    primaryColor: '#FFD700',
    secondaryColor: '#000000',
    gradient: 'from-yellow-400 to-yellow-500',
    gradientDark: 'from-gray-900 to-black',
    icon: 'Zap',
    emoji: '⚡',
    particleEffect: 'confetti',
  },
  'cyber-monday': {
    id: 'cyber-monday',
    name: 'Cyber Monday',
    primaryColor: '#00D4FF',
    secondaryColor: '#0099CC',
    gradient: 'from-cyan-400 to-blue-500',
    gradientDark: 'from-cyan-500 to-blue-600',
    icon: 'Monitor',
    emoji: '💻',
    particleEffect: 'confetti',
  },
  navidad: {
    id: 'navidad',
    name: 'Navidad',
    primaryColor: '#E30613',
    secondaryColor: '#34C759',
    gradient: 'from-red-500 to-green-500',
    gradientDark: 'from-red-700 to-green-700',
    icon: 'Gift',
    emoji: '🎄',
    particleEffect: 'snow',
  },
  'ano-nuevo': {
    id: 'ano-nuevo',
    name: 'Año Nuevo',
    primaryColor: '#FFD700',
    secondaryColor: '#C0C0C0',
    gradient: 'from-yellow-400 to-amber-500',
    gradientDark: 'from-yellow-500 to-amber-600',
    icon: 'Sparkles',
    emoji: '🎆',
    particleEffect: 'confetti',
  },
  'san-valentin': {
    id: 'san-valentin',
    name: 'San Valentín',
    primaryColor: '#FF2D55',
    secondaryColor: '#FF6B8A',
    gradient: 'from-pink-500 to-rose-500',
    gradientDark: 'from-pink-600 to-rose-700',
    icon: 'Heart',
    emoji: '💕',
    particleEffect: 'hearts',
  },
  verano: {
    id: 'verano',
    name: 'Verano',
    primaryColor: '#FF9500',
    secondaryColor: '#007AFF',
    gradient: 'from-orange-400 to-blue-500',
    gradientDark: 'from-orange-500 to-blue-600',
    icon: 'Sun',
    emoji: '☀️',
  },
  primavera: {
    id: 'primavera',
    name: 'Primavera',
    primaryColor: '#34C759',
    secondaryColor: '#FF9500',
    gradient: 'from-green-400 to-yellow-400',
    gradientDark: 'from-green-500 to-yellow-500',
    icon: 'Flower',
    emoji: '🌸',
  },
  'vuelta-cole': {
    id: 'vuelta-cole',
    name: 'Vuelta al Cole',
    primaryColor: '#FF9500',
    secondaryColor: '#007AFF',
    gradient: 'from-orange-500 to-blue-500',
    gradientDark: 'from-orange-600 to-blue-600',
    icon: 'BookOpen',
    emoji: '📚',
  },
  halloween: {
    id: 'halloween',
    name: 'Halloween',
    primaryColor: '#FF9500',
    secondaryColor: '#000000',
    gradient: 'from-orange-500 to-purple-600',
    gradientDark: 'from-orange-600 to-purple-800',
    icon: 'Ghost',
    emoji: '🎃',
  },
  'dia-padre': {
    id: 'dia-padre',
    name: 'Día del Padre',
    primaryColor: '#007AFF',
    secondaryColor: '#34C759',
    gradient: 'from-blue-500 to-green-500',
    gradientDark: 'from-blue-600 to-green-600',
    icon: 'Heart',
    emoji: '👨',
  },

  // ========================================
  // DEFAULT / GENERAL
  // ========================================
  general: {
    id: 'general',
    name: 'Soriano Mediadores',
    primaryColor: '#E30613',
    secondaryColor: '#B8050F',
    gradient: 'from-red-500 to-red-600',
    gradientDark: 'from-red-600 to-red-800',
    icon: 'Shield',
    emoji: '🛡️',
  },
}

// Helper to get theme by ID
export function getTheme(themeId: LandingThemeType): LandingTheme {
  return LANDING_THEMES[themeId] || LANDING_THEMES.general
}

// Helper to get theme color as CSS variable
export function getThemeStyles(themeId: LandingThemeType) {
  const theme = getTheme(themeId)
  return {
    '--theme-primary': theme.primaryColor,
    '--theme-secondary': theme.secondaryColor,
    '--theme-gradient': theme.gradient,
  } as React.CSSProperties
}

// Map insurance type to theme
export function getThemeForInsuranceType(insuranceType: string): LandingThemeType {
  const mapping: Record<string, LandingThemeType> = {
    AUTO: 'auto',
    HOGAR: 'hogar',
    SALUD: 'salud',
    VIDA: 'vida',
    DECESOS: 'decesos',
    MASCOTAS: 'mascotas',
    COMERCIO: 'comercio',
    COMUNIDADES: 'comunidades',
    VIAJE: 'viaje',
    MOTO: 'moto',
    ACCIDENTES: 'accidentes',
    RC_PROFESIONAL: 'rc-profesional',
    GENERAL: 'general',
  }
  return mapping[insuranceType] || 'general'
}
